# Generated by Django 4.1.1 on 2022-10-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_card_manager_card_asigned_to_project_admins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ref_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
