# Generated by Django 4.1.1 on 2022-10-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_ref_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='label_color',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='deadlineDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
