# Generated by Django 4.1.1 on 2023-01-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_card_label_color_alter_card_deadlinedate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='cardId',
            new_name='card',
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
