# Generated by Django 4.1.1 on 2023-01-21 10:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0007_notifictions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notifictions',
            new_name='Notifications',
        ),
    ]
